// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg0J7l2xKnpCePxfGZGyyKOf3Le6vpO-0',
    appId: '1:963301531292:web:9986b96ac2869eed8c9759',
    messagingSenderId: '963301531292',
    projectId: 'carenexus-57c87',
    authDomain: 'carenexus-57c87.firebaseapp.com',
    databaseURL: 'https://carenexus-57c87-default-rtdb.firebaseio.com',
    storageBucket: 'carenexus-57c87.firebasestorage.app',
    measurementId: 'G-N881L5CWNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMNs0W_BLs7RxusIoMw1txpORs3o-8TU',
    appId: '1:963301531292:android:c2852dad7bc2ce298c9759',
    messagingSenderId: '963301531292',
    projectId: 'carenexus-57c87',
    databaseURL: 'https://carenexus-57c87-default-rtdb.firebaseio.com',
    storageBucket: 'carenexus-57c87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN_Q68xKwgbIvsRJzY5BDAtpnn8kMZ-5I',
    appId: '1:963301531292:ios:6615bc68dbf3f2e88c9759',
    messagingSenderId: '963301531292',
    projectId: 'carenexus-57c87',
    databaseURL: 'https://carenexus-57c87-default-rtdb.firebaseio.com',
    storageBucket: 'carenexus-57c87.firebasestorage.app',
    iosClientId: '963301531292-607esfkeisjj362u7lt9d5pr0nm10hpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.careNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN_Q68xKwgbIvsRJzY5BDAtpnn8kMZ-5I',
    appId: '1:963301531292:ios:6615bc68dbf3f2e88c9759',
    messagingSenderId: '963301531292',
    projectId: 'carenexus-57c87',
    databaseURL: 'https://carenexus-57c87-default-rtdb.firebaseio.com',
    storageBucket: 'carenexus-57c87.firebasestorage.app',
    iosClientId: '963301531292-607esfkeisjj362u7lt9d5pr0nm10hpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.careNexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg0J7l2xKnpCePxfGZGyyKOf3Le6vpO-0',
    appId: '1:963301531292:web:9d24e4791c79d9d88c9759',
    messagingSenderId: '963301531292',
    projectId: 'carenexus-57c87',
    authDomain: 'carenexus-57c87.firebaseapp.com',
    databaseURL: 'https://carenexus-57c87-default-rtdb.firebaseio.com',
    storageBucket: 'carenexus-57c87.firebasestorage.app',
    measurementId: 'G-K9BZ2LJTE6',
  );

}